version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: app:latest
    volumes:
      - ./var/data:/app/var/data
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - server
networks:
  server:
    external: true